## Finanzas -- actualización y descuento

In [88]:
import pandas as pd
import numpy as np

In [89]:
df_todo = pd.read_excel('datos/datos_limpio_automovil.xlsx')

In [90]:
df_todo

,Unnamed: 0,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,...,Estudios_Escolar,Estudios_Grado Universitario,Estudios_Máster,Tipo_Jornada_Laboral_Autónomo,Tipo_Jornada_Laboral_Desempleado,Tipo_Jornada_Laboral_Jornada completa,Tipo_Jornada_Laboral_Tiempo parcial,Estado_Civil_Casado,Estado_Civil_Divorciado,Estado_Civil_Soltero
0,0,O77MPJ,26,19153,6973,706,9,1,19.05,36,...,False,True,False,False,False,True,False,False,False,True
1,8,IYOL1S,29,39531,40000,826,0,1,9.74,24,...,False,False,False,False,False,True,False,True,False,False
2,9,FRMZVN,29,40348,16448,740,9,1,14.73,24,...,False,False,True,False,False,True,False,False,False,True
3,26,YKHXVY,38,41732,42040,661,173,2,13.24,48,...,False,True,False,False,False,False,True,True,False,False
4,32,NHDJTK,35,35085,16406,759,181,1,9.74,36,...,True,False,False,False,False,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76919,510685,9DP3XV,36,45006,40252,746,144,1,12.74,36,...,False,True,False,False,False,True,False,True,False,False
76920,510686,R30LLT,42,44124,15509,574,246,2,8.00,24,...,False,True,False,True,False,False,False,False,False,True
76921,510687,W2Y3KE,44,84570,331820,791,246,2,6.90,60,...,False,False,False,False,False,False,True,True,False,False
76922,510695,WVJ9ZC,42,61642,19371,502,223,3,8.55,12,...,False,False,True,False,False,False,True,True,False,False
76923,510700,6903JQ,42,33486,33048,760,206,1,9.09,24,...,False,True,False,True,False,False,False,False,True,False

In [91]:
df_todo.columns

Index(['Unnamed: 0', 'ID', 'Edad', 'Ingresos', 'Monto_Inicial',
       'Scoring_Crediticio', 'Meses_Empleo', 'Num_Creditos', 'Ratio_Interes',
       'Duracion', 'Ratio_Deuda_Ingresos', 'Posesion_Hipoteca',
       'Personas_Cargo', 'Fiador', 'Impago', 'Prima', 'Estudios_Doctorado',
       'Estudios_Escolar', 'Estudios_Grado Universitario', 'Estudios_Máster',
       'Tipo_Jornada_Laboral_Autónomo', 'Tipo_Jornada_Laboral_Desempleado',
       'Tipo_Jornada_Laboral_Jornada completa',
       'Tipo_Jornada_Laboral_Tiempo parcial', 'Estado_Civil_Casado',
       'Estado_Civil_Divorciado', 'Estado_Civil_Soltero'],
      dtype='str')

In [92]:
df = df_todo[['ID', 'Monto_Inicial', 'Ratio_Interes', 'Duracion']]

In [93]:
df.copy()

           ID  Monto_Inicial  Ratio_Interes  Duracion
0      O77MPJ           6973          19.05        36
1      IYOL1S          40000           9.74        24
2      FRMZVN          16448          14.73        24
3      YKHXVY          42040          13.24        48
4      NHDJTK          16406           9.74        36
...       ...            ...            ...       ...
76919  9DP3XV          40252          12.74        36
76920  R30LLT          15509           8.00        24
76921  W2Y3KE         331820           6.90        60
76922  WVJ9ZC          19371           8.55        12
76923  6903JQ          33048           9.09        24

[76924 rows x 4 columns]

Me quedo con las columnas:
- ID: para saber que cliente es
- Monto inicial: Cantidad de dinero acordada.
- Ratio_Interes: El ratio de interés del préstamo (multiplicado por 100).
- Duracion: La duración del prestamo en meses.

Ya que son las variables que vamos a utilizar en las fórmulas.

In [94]:
df

           ID  Monto_Inicial  Ratio_Interes  Duracion
0      O77MPJ           6973          19.05        36
1      IYOL1S          40000           9.74        24
2      FRMZVN          16448          14.73        24
3      YKHXVY          42040          13.24        48
4      NHDJTK          16406           9.74        36
...       ...            ...            ...       ...
76919  9DP3XV          40252          12.74        36
76920  R30LLT          15509           8.00        24
76921  W2Y3KE         331820           6.90        60
76922  WVJ9ZC          19371           8.55        12
76923  6903JQ          33048           9.09        24

[76924 rows x 4 columns]

In [95]:
# Tipo de interés
df["i"] = df["Ratio_Interes"] / 100

# Duración expresada en años
df["n"] = df["Duracion"] / 12

# Capital inicial
df["C0_inicial"] = df["Monto_Inicial"]

# Capital futuro
df["Cn"] = df["C0_inicial"] * (1 + df["i"]) ** df["n"]

In [96]:
df

,ID,Monto_Inicial,Ratio_Interes,Duracion,i,n,C0_inicial,Cn
0,O77MPJ,6973,19.05,36,0.1905,3.0,6973,11765.431629
1,IYOL1S,40000,9.74,24,0.0974,2.0,40000,48171.470400
2,FRMZVN,16448,14.73,24,0.1473,2.0,16448,21650.457826
3,YKHXVY,42040,13.24,48,0.1324,4.0,42040,69129.298547
4,NHDJTK,16406,9.74,36,0.0974,3.0,16406,21681.911869
...,...,...,...,...,...,...,...,...
76919,9DP3XV,40252,12.74,36,0.1274,3.0,40252,57679.509093
76920,R30LLT,15509,8.00,24,0.0800,2.0,15509,18089.697600
76921,W2Y3KE,331820,6.90,60,0.0690,5.0,331820,463224.034761
76922,WVJ9ZC,19371,8.55,12,0.0855,1.0,19371,21027.220500
76923,6903JQ,33048,9.09,24,0.0909,2.0,33048,39329.195745

Descuento racional simple

In [97]:
# C0 = Cn / (1 + n*i)

df["C0_racional_simple"] = (df["Cn"] / (1 + (df["n"] * df["i"])))
df["C0_racional_simple"]

0          7486.752548
1         40317.601607
2         16723.665863
3         45194.363590
4         16779.068154
             ...
76919     41730.219283
76920     15594.566897
76921    344404.486811
76922     19371.000000
76923     33279.062231
Name: C0_racional_simple, Length: 76924, dtype: float64

Descuento racional compuesto

In [98]:
# C0 = Cn / (1+i)^n

df["C0_racional_compuesto"] = df["Cn"] / (1 + df["i"]) ** df["n"]

Descuento comercial simple

In [99]:
# C0 = Cn * (1 - n*d)

df["d"] = df["i"] / (1 + df["i"])

# Dado que el conjunto de datos únicamente proporciona el Ratio_Interes 
# y no una tasa de descuento comercial específica, 
# para poder aplicar los métodos de descuento comercial se ha supuesto que el tanto de descuento d 
# coincide con el tipo de interés i del préstamo.

df["C0_comercial_simple"] = (df["Cn"] * (1 - df["n"] * df["d"]))

In [100]:
print((df["C0_comercial_simple"] <= 0).sum())
print(df.loc[df["C0_comercial_simple"] <= 0, ["ID", "Ratio_Interes", "Duracion", "C0_comercial_simple"]].head())

0
Empty DataFrame
Columns: [ID, Ratio_Interes, Duracion, C0_comercial_simple]
Index: []

Descuento comercial compuesto

In [101]:
# C0 = Cn * (1-d)^n

df["C0_comercial_compuesto"] = (df["Cn"] * (1 - df["d"]) ** df["n"])

## Descuento en euros

In [102]:
df["D_racional_simple"] = (df["Cn"] - df["C0_racional_simple"])

df["D_racional_compuesto"] = (df["Cn"] - df["C0_racional_compuesto"])

df["D_comercial_simple"] = (df["Cn"] - df["C0_comercial_simple"])

df["D_comercial_compuesto"] = (df["Cn"] - df["C0_comercial_compuesto"])

In [104]:
# Criterio: hasta 12 meses régimen simple, más de 12 meses régimen compuesto
df["Regimen"] = np.where(df["Duracion"] <= 12, "simple", "compuesto")

df["C0_aplicable"] = np.where(
    df["Regimen"] == "simple",
    df["C0_racional_simple"],
    df["C0_racional_compuesto"],
)

print(df["Regimen"].value_counts())

Regimen
compuesto    69293
simple        7631
Name: count, dtype: int64

In [105]:
print(np.allclose(df["C0_comercial_compuesto"], df["C0_racional_compuesto"]))

True

## Resultados generales

In [103]:
columnas_resultados = [
    "ID",
    "Monto_Inicial",
    "Ratio_Interes",
    "Duracion",
    "Cn",
    "C0_racional_simple",
    "C0_racional_compuesto",
    "C0_comercial_simple",
    "C0_comercial_compuesto",
    "D_racional_simple",
    "D_racional_compuesto",
    "D_comercial_simple",
    "D_comercial_compuesto"
]

df[columnas_resultados].head(10)

,ID,Monto_Inicial,Ratio_Interes,Duracion,Cn,C0_racional_simple,C0_racional_compuesto,C0_comercial_simple,C0_comercial_compuesto,D_racional_simple,D_racional_compuesto,D_comercial_simple,D_comercial_compuesto
0,O77MPJ,6973,19.05,36,11765.431629,7486.752548,6973.0,6117.431481,6973.0,4278.679081,4792.431629,5648.000148,4792.431629
1,IYOL1S,40000,9.74,24,48171.470400,40317.601607,40000.0,39620.529600,40000.0,7853.868793,8171.470400,8550.940800,8171.470400
2,FRMZVN,16448,14.73,24,21650.457826,16723.665863,16448.0,16091.122974,16448.0,4926.791963,5202.457826,5559.334852,5202.457826
3,YKHXVY,42040,13.24,48,69129.298547,45194.363590,42040.0,36798.958993,42040.0,23934.934957,27089.298547,32330.339553,27089.298547
4,NHDJTK,16406,9.74,36,21681.911869,16779.068154,16406.0,15908.762016,16406.0,4902.843715,5275.911869,5773.149852,5275.911869
5,VIWISD,29965,9.32,12,32757.738000,29965.000000,29965.0,29965.000000,29965.0,2792.738000,2792.738000,2792.738000,2792.738000
6,SA6S9R,9918,8.73,36,12748.886891,10102.929623,9918.0,9678.038481,9918.0,2645.957268,2830.886891,3070.848411,2830.886891
7,DCJ69B,13642,4.83,36,15715.738817,13726.734927,13642.0,13543.449821,13642.0,1989.003891,2073.738817,2172.288996,2073.738817
8,E5TVKC,6093,12.50,24,7711.453125,6169.162500,6093.0,5997.796875,6093.0,1542.290625,1618.453125,1713.656250,1618.453125
9,N7B3CO,213418,14.71,24,280823.601785,216986.247709,213418.0,208799.973815,213418.0,63837.354076,67405.601785,72023.627971,67405.601785

In [108]:
cols_D = ["D_racional_simple", "D_racional_compuesto", "D_comercial_simple", "D_comercial_compuesto"]

# Solo préstamos a más de 12 meses, donde los métodos se diferencian

comp = df[df["Duracion"] > 12]
resumen = comp[cols_D].mean().round(2)
print(resumen)

D_racional_simple        16879.88
D_racional_compuesto     18708.60
D_comercial_simple       21728.03
D_comercial_compuesto    18708.60
dtype: float64

# Resultados (préstamos de más de 12 meses).

El descuento medio es:

- 16.879,88 € con racional simple
- 18.708,60 € con racional compuesto y comercial compuesto 
- 21.728,03 € con comercial simple

Interpretación:
- El racional compuesto descuenta unos 1.829 € más que el racional simple (≈ 10 %): el régimen compuesto capitaliza los intereses, así que a plazos largos el capital final contiene más intereses que descontar.
- El comercial simple descuenta unos 3.019 € más que el compuesto (≈ 16 %). Aplica d linealmente sobre el capital final, y por eso penaliza más cuanto mayor es la duración.
- El racional compuesto y el comercial compuesto coinciden porque d = i/(1+i) es el tanto de descuento equivalente a i: son el mismo cálculo escrito de dos formas.

Conclusión:

Como los préstamos son a plazos de 12 a 60 meses y Cn se calculó con capitalización compuesta, el método coherente en la mayoría de los casos (69.293 de 76.924) es el descuento racional compuesto, que devuelve exactamente el capital inicial. El comercial simple no es adecuado a plazos largos: sobrestima el descuento y, con d = i, incluso daba valores negativos.