# ACTUALIZACIÓN Y DESCUENTO

## Finanzas punto 1

**Objetivo.** Para cada préstamo de la cartera se calcula el capital futuro (C_n) y su valor actual (C_0) con cuatro métodos de descuento, se compara cuánto descuenta cada uno y se decide cuál es el coherente. En la última parte se aplican los conceptos del Tema 2-2 (equivalencia financiera y valores medios) al conjunto de la cartera.

## Datos

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_todo = pd.read_excel('datos/datos_limpio_automovil.xlsx')

In [4]:
df_todo

,Unnamed: 0,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,...,Estudios_Escolar,Estudios_Grado Universitario,Estudios_Máster,Tipo_Jornada_Laboral_Autónomo,Tipo_Jornada_Laboral_Desempleado,Tipo_Jornada_Laboral_Jornada completa,Tipo_Jornada_Laboral_Tiempo parcial,Estado_Civil_Casado,Estado_Civil_Divorciado,Estado_Civil_Soltero
0,0,O77MPJ,26,19153,6973,706,9,1,19.05,36,...,False,True,False,False,False,True,False,False,False,True
1,8,IYOL1S,29,39531,40000,826,0,1,9.74,24,...,False,False,False,False,False,True,False,True,False,False
2,9,FRMZVN,29,40348,16448,740,9,1,14.73,24,...,False,False,True,False,False,True,False,False,False,True
3,26,YKHXVY,38,41732,42040,661,173,2,13.24,48,...,False,True,False,False,False,False,True,True,False,False
4,32,NHDJTK,35,35085,16406,759,181,1,9.74,36,...,True,False,False,False,False,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76919,510685,9DP3XV,36,45006,40252,746,144,1,12.74,36,...,False,True,False,False,False,True,False,True,False,False
76920,510686,R30LLT,42,44124,15509,574,246,2,8.00,24,...,False,True,False,True,False,False,False,False,False,True
76921,510687,W2Y3KE,44,84570,331820,791,246,2,6.90,60,...,False,False,False,False,False,False,True,True,False,False
76922,510695,WVJ9ZC,42,61642,19371,502,223,3,8.55,12,...,False,False,True,False,False,False,True,True,False,False
76923,510700,6903JQ,42,33486,33048,760,206,1,9.09,24,...,False,True,False,True,False,False,False,False,True,False

In [5]:
df_todo.columns

Index(['Unnamed: 0', 'ID', 'Edad', 'Ingresos', 'Monto_Inicial',
       'Scoring_Crediticio', 'Meses_Empleo', 'Num_Creditos', 'Ratio_Interes',
       'Duracion', 'Ratio_Deuda_Ingresos', 'Posesion_Hipoteca',
       'Personas_Cargo', 'Fiador', 'Impago', 'Prima', 'Estudios_Doctorado',
       'Estudios_Escolar', 'Estudios_Grado Universitario', 'Estudios_Máster',
       'Tipo_Jornada_Laboral_Autónomo', 'Tipo_Jornada_Laboral_Desempleado',
       'Tipo_Jornada_Laboral_Jornada completa',
       'Tipo_Jornada_Laboral_Tiempo parcial', 'Estado_Civil_Casado',
       'Estado_Civil_Divorciado', 'Estado_Civil_Soltero'],
      dtype='str')

In [6]:
df = df_todo[['ID', 'Monto_Inicial', 'Ratio_Interes', 'Duracion']].copy()

In [7]:
df.head()

       ID  Monto_Inicial  Ratio_Interes  Duracion
0  O77MPJ           6973          19.05        36
1  IYOL1S          40000           9.74        24
2  FRMZVN          16448          14.73        24
3  YKHXVY          42040          13.24        48
4  NHDJTK          16406           9.74        36

Me quedo con las columnas:
- ID: para saber que cliente es
- Monto inicial: Cantidad de dinero acordada.
- Ratio_Interes: El ratio de interés del préstamo (multiplicado por 100).
- Duracion: La duración del prestamo en meses.

Ya que son las variables que vamos a utilizar en las fórmulas.

In [8]:
df

           ID  Monto_Inicial  Ratio_Interes  Duracion
0      O77MPJ           6973          19.05        36
1      IYOL1S          40000           9.74        24
2      FRMZVN          16448          14.73        24
3      YKHXVY          42040          13.24        48
4      NHDJTK          16406           9.74        36
...       ...            ...            ...       ...
76919  9DP3XV          40252          12.74        36
76920  R30LLT          15509           8.00        24
76921  W2Y3KE         331820           6.90        60
76922  WVJ9ZC          19371           8.55        12
76923  6903JQ          33048           9.09        24

[76924 rows x 4 columns]

## Capital futuro

In [9]:
# Tipo de interés
df["i"] = df["Ratio_Interes"] / 100

# Duración expresada en años
df["n"] = df["Duracion"] / 12

# Capital inicial
df["C0_inicial"] = df["Monto_Inicial"]

# Capital futuro
df["Cn"] = df["C0_inicial"] * (1 + df["i"]) ** df["n"]

In [10]:
df

,ID,Monto_Inicial,Ratio_Interes,Duracion,i,n,C0_inicial,Cn
0,O77MPJ,6973,19.05,36,0.1905,3.0,6973,11765.431629
1,IYOL1S,40000,9.74,24,0.0974,2.0,40000,48171.470400
2,FRMZVN,16448,14.73,24,0.1473,2.0,16448,21650.457826
3,YKHXVY,42040,13.24,48,0.1324,4.0,42040,69129.298547
4,NHDJTK,16406,9.74,36,0.0974,3.0,16406,21681.911869
...,...,...,...,...,...,...,...,...
76919,9DP3XV,40252,12.74,36,0.1274,3.0,40252,57679.509093
76920,R30LLT,15509,8.00,24,0.0800,2.0,15509,18089.697600
76921,W2Y3KE,331820,6.90,60,0.0690,5.0,331820,463224.034761
76922,WVJ9ZC,19371,8.55,12,0.0855,1.0,19371,21027.220500
76923,6903JQ,33048,9.09,24,0.0909,2.0,33048,39329.195745

## Cuatro métodos de descuento

Descuento racional simple

In [11]:
# C0 = Cn / (1 + n*i)

df["C0_racional_simple"] = (df["Cn"] / (1 + (df["n"] * df["i"])))
df["C0_racional_simple"]

0          7486.752548
1         40317.601607
2         16723.665863
3         45194.363590
4         16779.068154
             ...
76919     41730.219283
76920     15594.566897
76921    344404.486811
76922     19371.000000
76923     33279.062231
Name: C0_racional_simple, Length: 76924, dtype: float64

Descuento racional compuesto

In [27]:
# C0 = Cn / (1+i)^n

df["C0_racional_compuesto"] = df["Cn"] / (1 + df["i"]) ** df["n"]
df["C0_racional_compuesto"]

0          6973.0
1         40000.0
2         16448.0
3         42040.0
4         16406.0
           ...
76919     40252.0
76920     15509.0
76921    331820.0
76922     19371.0
76923     33048.0
Name: C0_racional_compuesto, Length: 76924, dtype: float64

Descuento comercial simple

In [ ]:
# C0 = Cn * (1 - n*d)

df["d"] = df["i"] / (1 + df["i"])

df["C0_comercial_simple"] = (df["Cn"] * (1 - df["n"] * df["d"]))
df["C0_comercial_simple"]

0          6117.431481
1         39620.529600
2         16091.122974
3         36798.958993
4         15908.762016
             ...
76919     38125.572269
76920     15409.742400
76921    313727.035704
76922     19371.000000
76923     32774.930655
Name: C0_comercial_simple, Length: 76924, dtype: float64

In [29]:
# Comprobación: con este d ningún préstamo da un valor actual negativo o nulo. 
# En una prueba previa con d=i sí aparecían valores negativos en plazos largos, porque n\d podía superar 1.

print((df["C0_comercial_simple"] <= 0).sum())
print(df.loc[df["C0_comercial_simple"] <= 0, ["ID", "Ratio_Interes", "Duracion", "C0_comercial_simple"]].head())

0
Empty DataFrame
Columns: [ID, Ratio_Interes, Duracion, C0_comercial_simple]
Index: []

Descuento comercial compuesto

In [15]:
# C0 = Cn * (1-d)^n

df["C0_comercial_compuesto"] = (df["Cn"] * (1 - df["d"]) ** df["n"])

In [30]:
# Como 1-d = 1/(1+i), el comercial compuesto C_n(1-d)^n es el mismo cálculo que el racional compuesto C_n/(1+i)^n

## Descuento en euros

El descuento de cada préstamo es la diferencia entre el capital futuro y el valor actual: D = C_n - C_0

In [16]:
df["D_racional_simple"] = (df["Cn"] - df["C0_racional_simple"])

df["D_racional_compuesto"] = (df["Cn"] - df["C0_racional_compuesto"])

df["D_comercial_simple"] = (df["Cn"] - df["C0_comercial_simple"])

df["D_comercial_compuesto"] = (df["Cn"] - df["C0_comercial_compuesto"])

In [17]:
# Criterio: hasta 12 meses régimen simple, más de 12 meses régimen compuesto
df["Regimen"] = np.where(df["Duracion"] <= 12, "simple", "compuesto")

df["C0_aplicable"] = np.where(
    df["Regimen"] == "simple",
    df["C0_racional_simple"],
    df["C0_racional_compuesto"],
)

print(df["Regimen"].value_counts())

Regimen
compuesto    69293
simple        7631
Name: count, dtype: int64

## Resultados generales

In [19]:
columnas_resultados = [
    "ID",
    "Monto_Inicial",
    "Ratio_Interes",
    "Duracion",
    "Cn",
    "C0_racional_simple",
    "C0_racional_compuesto",
    "C0_comercial_simple",
    "C0_comercial_compuesto",
    "D_racional_simple",
    "D_racional_compuesto",
    "D_comercial_simple",
    "D_comercial_compuesto"
]

df[columnas_resultados].head(10)

,ID,Monto_Inicial,Ratio_Interes,Duracion,Cn,C0_racional_simple,C0_racional_compuesto,C0_comercial_simple,C0_comercial_compuesto,D_racional_simple,D_racional_compuesto,D_comercial_simple,D_comercial_compuesto
0,O77MPJ,6973,19.05,36,11765.431629,7486.752548,6973.0,6117.431481,6973.0,4278.679081,4792.431629,5648.000148,4792.431629
1,IYOL1S,40000,9.74,24,48171.470400,40317.601607,40000.0,39620.529600,40000.0,7853.868793,8171.470400,8550.940800,8171.470400
2,FRMZVN,16448,14.73,24,21650.457826,16723.665863,16448.0,16091.122974,16448.0,4926.791963,5202.457826,5559.334852,5202.457826
3,YKHXVY,42040,13.24,48,69129.298547,45194.363590,42040.0,36798.958993,42040.0,23934.934957,27089.298547,32330.339553,27089.298547
4,NHDJTK,16406,9.74,36,21681.911869,16779.068154,16406.0,15908.762016,16406.0,4902.843715,5275.911869,5773.149852,5275.911869
5,VIWISD,29965,9.32,12,32757.738000,29965.000000,29965.0,29965.000000,29965.0,2792.738000,2792.738000,2792.738000,2792.738000
6,SA6S9R,9918,8.73,36,12748.886891,10102.929623,9918.0,9678.038481,9918.0,2645.957268,2830.886891,3070.848411,2830.886891
7,DCJ69B,13642,4.83,36,15715.738817,13726.734927,13642.0,13543.449821,13642.0,1989.003891,2073.738817,2172.288996,2073.738817
8,E5TVKC,6093,12.50,24,7711.453125,6169.162500,6093.0,5997.796875,6093.0,1542.290625,1618.453125,1713.656250,1618.453125
9,N7B3CO,213418,14.71,24,280823.601785,216986.247709,213418.0,208799.973815,213418.0,63837.354076,67405.601785,72023.627971,67405.601785

In [20]:
cols_D = ["D_racional_simple", "D_racional_compuesto", "D_comercial_simple", "D_comercial_compuesto"]

# Solo préstamos a más de 12 meses, donde los métodos se diferencian

comp = df[df["Duracion"] > 12]
resumen = comp[cols_D].mean().round(2)
print(resumen)

D_racional_simple        16879.88
D_racional_compuesto     18708.60
D_comercial_simple       21728.03
D_comercial_compuesto    18708.60
dtype: float64

**Método**      ----------       **Descuento medio**

Racional simple --> 16.879,88 € 

Racional compuesto (= comercial compuesto) --> 18.708,60 € 

Comercial simple --> 21.728,03 €

# Resultados (préstamos de más de 12 meses).

El descuento medio es:

- 16.879,88 € con racional simple
- 18.708,60 € con racional compuesto y comercial compuesto 
- 21.728,03 € con comercial simple

Interpretación

- **Racional compuesto frente a racional simple:** descuenta unos 1.829 € más (10,8 %). Como (1+i)^n > 1 + n\,i cuando n>1, dividir por el factor compuesto da un C_0 menor, es decir, un descuento mayor: el compuesto reconoce los intereses sobre intereses.
- **Comercial simple frente a comercial compuesto:** descuenta unos 3.019 € más (16,1 %). El simple resta n\d de golpe y de forma lineal, mientras que el compuesto multiplica por (1-d)^n > 1 - n\d, así que resta menos. La diferencia crece con la duración.
- **Racional compuesto y comercial compuesto coinciden** porque 1-d = 1/(1+i): son el mismo cálculo escrito de dos formas.

Conclusión:

Como los préstamos son a plazos de 12 a 60 meses y Cn se calculó con capitalización compuesta, el método coherente en la mayoría de los casos (69.293 de 76.924) es el descuento racional compuesto, que devuelve exactamente el capital inicial. El comercial simple no es adecuado a plazos largos: sobrestima el descuento y, con d = i, incluso daba valores negativos.

## Valores medios y equivalencias financieras (Tema 2-2)

Hasta aquí se ha trabajado préstamo a préstamo. Ahora la cartera se trata como un conjunto de capitales C_i (los C_n de cada préstamo) con vencimientos n_i, y se resume con valores medios. Las fórmulas del Tema 2-2 suponen un único tipo; como cada préstamo tiene el suyo, se calculan por grupos de igual plazo o con medias ponderadas.

In [21]:
# Monto_Inicial (hoy) y Cn (al vencimiento) son financieramente equivalentes al tipo i.

In [22]:
# Tipo medio por plazo (ponderado por capital; el PDF exige mismo plazo)

def tipo_medio(x):
    return np.average(x["i"], weights=x["Monto_Inicial"])
 
im_por_plazo = df.groupby("Duracion").apply(tipo_medio, include_groups=False)
im_por_plazo = (im_por_plazo * 100).round(2).rename("i_medio_%")
print(im_por_plazo)

Duracion
12    10.65
24    10.62
36    10.68
48    10.66
60    10.65
Name: i_medio_%, dtype: float64

In [23]:
# Vencimiento medio de la cartera: nm = sum(Cn * n) / sum(Cn)

nm = (df["Cn"] * df["n"]).sum() / df["Cn"].sum()
print(f"Vencimiento medio: {nm:.4f} años")

Vencimiento medio: 3.2564 años

In [24]:
# Capital único hoy (nt = 0): valor actual de toda la cartera

Ct_hoy = df["C0_racional_compuesto"].sum()
print(f"Capital único hoy: {Ct_hoy:,.2f} €  (suma Monto_Inicial: {df['Monto_Inicial'].sum():,.2f} €)")

Capital único hoy: 3,440,824,668.00 €  (suma Monto_Inicial: 3,440,824,668.00 €)

In [25]:
# Vencimiento común: pago único de sum(Cn), descuento comercial compuesto

# Ct * (1-d)^nt = sum(Ci * (1-d)^ni)  ->  nt = ln(VA / Ct) / ln(1-d)
# El PDF supone un único d: usamos el d medio ponderado por Cn.

def vencimiento_comun(x):
    Ct = x["Cn"].sum()
    VA = (x["Cn"] * (1 - x["d"]) ** x["n"]).sum()
    d_m = np.average(x["d"], weights=x["Cn"])
    return np.log(VA / Ct) / np.log(1 - d_m)
 
nt_global = vencimiento_comun(df)
print(f"Vencimiento común global: {nt_global:.4f} años  vs  nm = {nm:.4f} años")

Vencimiento común global: 3.1498 años  vs  nm = 3.2564 años

In [26]:
# Vencimiento común por plazo, comparado con el plazo real

nt_plazo = df.groupby("Duracion").apply(vencimiento_comun, include_groups=False).rename("nt_años")
tabla = nt_plazo.to_frame()
tabla["plazo_años"] = tabla.index / 12
tabla["diferencia"] = tabla["nt_años"] - tabla["plazo_años"]
print(tabla.round(4))

          nt_años  plazo_años  diferencia
Duracion
12         1.0000         1.0      0.0000
24         1.9882         2.0     -0.0118
36         2.9664         3.0     -0.0336
48         3.9332         4.0     -0.0668
60         4.8835         5.0     -0.1165

### Interpretación

- **Tipo medio:** ronda el 10,65 % en todos los plazos (10,62 %–10,68 %), es decir, el tipo no depende de la duración del préstamo.
- **Vencimiento medio:** $n_m$ = 3,2564 años (≈ 3 años y 3 meses).
- **Vencimiento común:** $n_t$ = 3,1498 años (≈ 3 años y 2 meses), anterior a $n_m$. Con descuento compuesto el tipo sí influye en el vencimiento: como $(1-d)^n$ es convexa, el pago único debe adelantarse respecto al vencimiento medio. En el ejemplo de la diapositiva 28 también sale $n_t < n_m$ (2,2063 frente a 2,2222). Además influye el uso de un $d$ medio.
- **Por plazo:** a 12 meses $n_t$ coincide con el plazo (1,0000) y se queda por debajo cuanto más largo es el préstamo (−0,01 años a 24 meses, −0,12 a 60). No es un efecto económico real: aparece porque cada préstamo tiene su propio $d$ y aquí se usa uno medio, mientras que la fórmula del Tema 2-2 supone un $d$ único. A 12 meses desaparece porque el descuento es lineal en un solo año.
- **Capital medio ($C_m$):** no aplica, porque cada préstamo tiene un único pago y no una serie de pagos de importes distintos.

## 8. Conclusiones

1. **Equivalencia.** `Monto_Inicial` y $C_n$ son equivalentes al tipo $i$: el descuento racional compuesto devuelve exactamente el capital inicial, y el capital único hoy de la cartera (3.440.824.668 €) coincide con la suma de `Monto_Inicial`.
2. **Método aplicado.** Se usa el descuento racional con el régimen que corresponde al plazo: simple hasta 12 meses (7.631 préstamos) y compuesto por encima (69.293). Es un mismo criterio, deshacer la capitalización con la misma ley y el mismo tipo, aplicado con la ley de cada plazo. A 12 meses ambas leyes coinciden, así que la diferencia real está en los préstamos de más de 12 meses.
3. **Por qué no el comercial.** Exige un tanto de descuento que el dataset no tiene. El comercial simple sobrestima el descuento a plazos largos (21.728 € de media frente a 18.709 €), y el comercial compuesto solo coincide con el racional compuesto porque se tomó $d = i/(1+i)$.
4. **Impacto de la elección.** En préstamos de más de 12 meses el descuento medio es 16.879,88 € (racional simple), 18.708,60 € (compuesto) y 21.728,03 € (comercial simple): según el método, el resultado varía hasta un 29 %.
5. **Cartera.** Tipo medio ≈ 10,65 % en todos los plazos, vencimiento medio de 3,2564 años y vencimiento común de 3,1498 años.
6. **Limitación.** Las fórmulas de valores medios del Tema 2-2 suponen un único tanto de descuento y la cartera tiene uno por préstamo. Por eso se agrupa por plazo o se usa un $d$ medio ponderado, y los resultados de $n_t$ son aproximados.