# Sistemas de amortización

In [32]:
import pandas as pd 
import numpy as np

In [33]:
datos= pd.read_excel("datos/datos_limpio_automovil.xlsx")

In [34]:
datos.head()

,Unnamed: 0,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,...,Estudios_Escolar,Estudios_Grado Universitario,Estudios_Máster,Tipo_Jornada_Laboral_Autónomo,Tipo_Jornada_Laboral_Desempleado,Tipo_Jornada_Laboral_Jornada completa,Tipo_Jornada_Laboral_Tiempo parcial,Estado_Civil_Casado,Estado_Civil_Divorciado,Estado_Civil_Soltero
0,0,O77MPJ,26,19153,6973,706,9,1,19.05,36,...,False,True,False,False,False,True,False,False,False,True
1,8,IYOL1S,29,39531,40000,826,0,1,9.74,24,...,False,False,False,False,False,True,False,True,False,False
2,9,FRMZVN,29,40348,16448,740,9,1,14.73,24,...,False,False,True,False,False,True,False,False,False,True
3,26,YKHXVY,38,41732,42040,661,173,2,13.24,48,...,False,True,False,False,False,False,True,True,False,False
4,32,NHDJTK,35,35085,16406,759,181,1,9.74,36,...,True,False,False,False,False,True,False,True,False,False

In [35]:
datos.columns

Index(['Unnamed: 0', 'ID', 'Edad', 'Ingresos', 'Monto_Inicial',
       'Scoring_Crediticio', 'Meses_Empleo', 'Num_Creditos', 'Ratio_Interes',
       'Duracion', 'Ratio_Deuda_Ingresos', 'Posesion_Hipoteca',
       'Personas_Cargo', 'Fiador', 'Impago', 'Prima', 'Estudios_Doctorado',
       'Estudios_Escolar', 'Estudios_Grado Universitario', 'Estudios_Máster',
       'Tipo_Jornada_Laboral_Autónomo', 'Tipo_Jornada_Laboral_Desempleado',
       'Tipo_Jornada_Laboral_Jornada completa',
       'Tipo_Jornada_Laboral_Tiempo parcial', 'Estado_Civil_Casado',
       'Estado_Civil_Divorciado', 'Estado_Civil_Soltero'],
      dtype='str')

In [36]:
datos.shape

(76924, 27)

In [37]:
datos.info()

<class 'pandas.DataFrame'>
RangeIndex: 76924 entries, 0 to 76923
Data columns (total 27 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Unnamed: 0                             76924 non-null  int64
 1   ID                                     76924 non-null  str
 2   Edad                                   76924 non-null  int64
 3   Ingresos                               76924 non-null  int64
 4   Monto_Inicial                          76924 non-null  int64
 5   Scoring_Crediticio                     76924 non-null  int64
 6   Meses_Empleo                           76924 non-null  int64
 7   Num_Creditos                           76924 non-null  int64
 8   Ratio_Interes                          76924 non-null  float64
 9   Duracion                               76924 non-null  int64
 10  Ratio_Deuda_Ingresos                   76924 non-null  float64
 11  Posesion_Hipoteca                      76924 non-null  int64
 12  Personas_Cargo                         76924 non-null  int64
 13  Fiador                                 76924 non-null  int64
 14  Impago                                 76924 non-null  int64
 15  Prima                                  76924 non-null  float64
 16  Estudios_Doctorado                     76924 non-null  bool
 17  Estudios_Escolar                       76924 non-null  bool
 18  Estudios_Grado Universitario           76924 non-null  bool
 19  Estudios_Máster                        76924 non-null  bool
 20  Tipo_Jornada_Laboral_Autónomo          76924 non-null  bool
 21  Tipo_Jornada_Laboral_Desempleado       76924 non-null  bool
 22  Tipo_Jornada_Laboral_Jornada completa  76924 non-null  bool
 23  Tipo_Jornada_Laboral_Tiempo parcial    76924 non-null  bool
 24  Estado_Civil_Casado                    76924 non-null  bool
 25  Estado_Civil_Divorciado                76924 non-null  bool
 26  Estado_Civil_Soltero                   76924 non-null  bool
dtypes: bool(11), float64(3), int64(12), str(1)
memory usage: 10.2 MB

# 1- Cuadros de amortización

Cambiamos los nombres para hacer mas facil la formula 
- Monto inicial-->capital_prestado
- Ratio Interes -->  interés_anual.
- Duración --> num_meses

In [38]:
datos = datos.rename(columns={
    "Monto_Inicial": "capital_prestado",
    "Ratio_Interes": "interes_anual",
    "Duracion": "num_meses"
})
print(datos.info())

<class 'pandas.DataFrame'>
RangeIndex: 76924 entries, 0 to 76923
Data columns (total 27 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Unnamed: 0                             76924 non-null  int64
 1   ID                                     76924 non-null  str
 2   Edad                                   76924 non-null  int64
 3   Ingresos                               76924 non-null  int64
 4   capital_prestado                       76924 non-null  int64
 5   Scoring_Crediticio                     76924 non-null  int64
 6   Meses_Empleo                           76924 non-null  int64
 7   Num_Creditos                           76924 non-null  int64
 8   interes_anual                          76924 non-null  float64
 9   num_meses                              76924 non-null  int64
 10  Ratio_Deuda_Ingresos                   76924 non-null  float64
 11  Posesion_Hipoteca                      76924 non-null  int64
 12  Personas_Cargo                         76924 non-null  int64
 13  Fiador                                 76924 non-null  int64
 14  Impago                                 76924 non-null  int64
 15  Prima                                  76924 non-null  float64
 16  Estudios_Doctorado                     76924 non-null  bool
 17  Estudios_Escolar                       76924 non-null  bool
 18  Estudios_Grado Universitario           76924 non-null  bool
 19  Estudios_Máster                        76924 non-null  bool
 20  Tipo_Jornada_Laboral_Autónomo          76924 non-null  bool
 21  Tipo_Jornada_Laboral_Desempleado       76924 non-null  bool
 22  Tipo_Jornada_Laboral_Jornada completa  76924 non-null  bool
 23  Tipo_Jornada_Laboral_Tiempo parcial    76924 non-null  bool
 24  Estado_Civil_Casado                    76924 non-null  bool
 25  Estado_Civil_Divorciado                76924 non-null  bool
 26  Estado_Civil_Soltero                   76924 non-null  bool
dtypes: bool(11), float64(3), int64(12), str(1)
memory usage: 10.2 MB
None

# Sistema Francés

La cuota es constante.
Los intereses disminuyen.
La amortización de capital aumenta.

Crear la función del sistema francés

In [39]:
def cuadro_frances(capital, interes_anual, meses):

    # Pasar el interés anual (%) a interés mensual decimal
    i = (interes_anual / 100) / 12

    # Cuota constante
    cuota = capital * (i * (1 + i)**meses) / ((1 + i)**meses - 1)

    saldo = capital

    tabla = []

    for periodo in range(1, meses + 1):

        intereses = saldo * i

        capital_amortizado = cuota - intereses

        saldo = saldo - capital_amortizado

        tabla.append([
            periodo,
            round(cuota, 2),
            round(intereses, 2),
            round(capital_amortizado, 2),
            round(max(0, saldo), 2)
        ])

    return pd.DataFrame(
        tabla,
        columns=[
            "Periodo",
            "Cuota",
            "Intereses",
            "Capital_Amortizado",
            "Saldo_Pendiente"
        ]
    )

Probamos que funciona con un prestamo

# Sistema Alemán

La amortización es constante.

Funcion del sistema alemán

In [40]:
def cuadro_aleman(capital, interes_anual, meses):

    i = (interes_anual / 100) / 12

    amortizacion_constante = capital / meses

    saldo = capital

    tabla = []

    for periodo in range(1, meses + 1):

        intereses = saldo * i

        cuota = amortizacion_constante + intereses

        saldo = saldo - amortizacion_constante

        tabla.append([
            periodo,
            round(cuota, 2),
            round(intereses, 2),
            round(amortizacion_constante, 2),
            round(max(0, saldo), 2)
        ])

    return pd.DataFrame(
        tabla,
        columns=[
            "Periodo",
            "Cuota",
            "Intereses",
            "Capital_Amortizado",
            "Saldo_Pendiente"
        ]
    )

Probarlo con el primer préstamo

In [41]:
capital = datos.loc[0, "capital_prestado"]
interes = datos.loc[0, "interes_anual"]
meses = datos.loc[0, "num_meses"]

frances = cuadro_frances(capital, interes, meses)
aleman = cuadro_aleman(capital, interes, meses)

print("CUADRO FRANCÉS")
print(frances.head())

print("\nCUADRO ALEMÁN")
print(aleman.head())

CUADRO FRANCÉS
   Periodo   Cuota  Intereses  Capital_Amortizado  Saldo_Pendiente
0        1  255.78     110.70              145.08          6827.92
1        2  255.78     108.39              147.39          6680.53
2        3  255.78     106.05              149.73          6530.81
3        4  255.78     103.68              152.10          6378.70
4        5  255.78     101.26              154.52          6224.19

CUADRO ALEMÁN
   Periodo   Cuota  Intereses  Capital_Amortizado  Saldo_Pendiente
0        1  304.39     110.70              193.69          6779.31
1        2  301.32     107.62              193.69          6585.61
2        3  298.24     104.55              193.69          6391.92
3        4  295.17     101.47              193.69          6198.22
4        5  292.09      98.40              193.69          6004.53

Cuadro frances para todos los prestamos

In [42]:
cuadros_frances = {}

for _, fila in datos.iterrows():

    cuadros_frances[fila["ID"]] = cuadro_frances(
        fila["capital_prestado"],
        fila["interes_anual"],
        fila["num_meses"]
    )

Cuadro aleman para todos los prestamos

In [43]:
cuadros_aleman = {}

for _, fila in datos.iterrows():

    cuadros_aleman[fila["ID"]] = cuadro_aleman(
        fila["capital_prestado"],
        fila["interes_anual"],
        fila["num_meses"]
    )

Ver el cuadro de un préstamo concreto

In [44]:
id_prestamo = datos.loc[0, "ID"]

print(cuadros_frances[id_prestamo])
print(cuadros_aleman[id_prestamo])
print(cuadros_aleman[id_prestamo])

    Periodo   Cuota  Intereses  Capital_Amortizado  Saldo_Pendiente
0         1  255.78     110.70              145.08          6827.92
1         2  255.78     108.39              147.39          6680.53
2         3  255.78     106.05              149.73          6530.81
3         4  255.78     103.68              152.10          6378.70
4         5  255.78     101.26              154.52          6224.19
5         6  255.78      98.81              156.97          6067.22
6         7  255.78      96.32              159.46          5907.76
7         8  255.78      93.79              161.99          5745.76
8         9  255.78      91.21              164.56          5581.20
9        10  255.78      88.60              167.18          5414.02
10       11  255.78      85.95              169.83          5244.19
11       12  255.78      83.25              172.53          5071.66
12       13  255.78      80.51              175.27          4896.40
13       14  255.78      77.73              178.05          4718.35
14       15  255.78      74.90              180.87          4537.47
15       16  255.78      72.03              183.75          4353.73
16       17  255.78      69.12              186.66          4167.06
17       18  255.78      66.15              189.63          3977.44
18       19  255.78      63.14              192.64          3784.80
19       20  255.78      60.08              195.70          3589.11
20       21  255.78      56.98              198.80          3390.30
21       22  255.78      53.82              201.96          3188.35
22       23  255.78      50.61              205.16          2983.18
23       24  255.78      47.36              208.42          2774.76
24       25  255.78      44.05              211.73          2563.03
25       26  255.78      40.69              215.09          2347.94
26       27  255.78      37.27              218.51          2129.44
27       28  255.78      33.80              221.97          1907.46
28       29  255.78      30.28              225.50          1681.96
29       30  255.78      26.70              229.08          1452.89
30       31  255.78      23.06              232.71          1220.17
31       32  255.78      19.37              236.41           983.76
32       33  255.78      15.62              240.16           743.60
33       34  255.78      11.80              243.97           499.63
34       35  255.78       7.93              247.85           251.78
35       36  255.78       4.00              251.78             0.00
    Periodo   Cuota  Intereses  Capital_Amortizado  Saldo_Pendiente
0         1  304.39     110.70              193.69          6779.31
1         2  301.32     107.62              193.69          6585.61
2         3  298.24     104.55              193.69          6391.92
3         4  295.17     101.47              193.69          6198.22
4         5  292.09      98.40              193.69          6004.53
5         6  289.02      95.32              193.69          5810.83
6         7  285.94      92.25              193.69          5617.14
7         8  282.87      89.17              193.69          5423.44
8         9  279.79      86.10              193.69          5229.75
9        10  276.72      83.02              193.69          5036.06
10       11  273.64      79.95              193.69          4842.36
11       12  270.57      76.87              193.69          4648.67
12       13  267.49      73.80              193.69          4454.97
13       14  264.42      70.72              193.69          4261.28
14       15  261.34      67.65              193.69          4067.58
15       16  258.27      64.57              193.69          3873.89
16       17  255.19      61.50              193.69          3680.19
17       18  252.12      58.42              193.69          3486.50
18       19  249.04      55.35              193.69          3292.81
19       20  245.97      52.27              193.69          3099.11
20       21  242.89      49.20              193.69          2905.42
21       22  239.82      46.12              193.69          2711.72
22       23  236.74      43.05              193.69          2518.03
23       24  233.67      39.97              193.69          2324.33
24       25  230.59      36.90              193.69          2130.64
25       26  227.52      33.82              193.69          1936.94
26       27  224.44      30.75              193.69          1743.25
27       28  221.37      27.67              193.69          1549.56
28       29  218.29      24.60              193.69          1355.86
29       30  215.22      21.52              193.69          1162.17
30       31  212.14      18.45              193.69           968.47
31       32  209.07      15.37              193.69           774.78
32       33  205.99      12.30              193.69           581.08
33       34  202.92       9.22              193.69           387.39
34       35  199.84       6.15              193.69           193.69
35       36  196.77       3.07              193.69             0.00
    Periodo   Cuota  Intereses  Capital_Amortizado  Saldo_Pendiente
0         1  304.39     110.70              193.69          6779.31
1         2  301.32     107.62              193.69          6585.61
2         3  298.24     104.55              193.69          6391.92
3         4  295.17     101.47              193.69          6198.22
4         5  292.09      98.40              193.69          6004.53
5         6  289.02      95.32              193.69          5810.83
6         7  285.94      92.25              193.69          5617.14
7         8  282.87      89.17              193.69          5423.44
8         9  279.79      86.10              193.69          5229.75
9        10  276.72      83.02              193.69          5036.06
10       11  273.64      79.95              193.69          4842.36
11       12  270.57      76.87              193.69          4648.67
12       13  267.49      73.80              193.69          4454.97
13       14  264.42      70.72              193.69          4261.28
14       15  261.34      67.65              193.69          4067.58
15       16  258.27      64.57              193.69          3873.89
16       17  255.19      61.50              193.69          3680.19
17       18  252.12      58.42              193.69          3486.50
18       19  249.04      55.35              193.69          3292.81
19       20  245.97      52.27              193.69          3099.11
20       21  242.89      49.20              193.69          2905.42
21       22  239.82      46.12              193.69          2711.72
22       23  236.74      43.05              193.69          2518.03
23       24  233.67      39.97              193.69          2324.33
24       25  230.59      36.90              193.69          2130.64
25       26  227.52      33.82              193.69          1936.94
26       27  224.44      30.75              193.69          1743.25
27       28  221.37      27.67              193.69          1549.56
28       29  218.29      24.60              193.69          1355.86
29       30  215.22      21.52              193.69          1162.17
30       31  212.14      18.45              193.69           968.47
31       32  209.07      15.37              193.69           774.78
32       33  205.99      12.30              193.69           581.08
33       34  202.92       9.22              193.69           387.39
34       35  199.84       6.15              193.69           193.69
35       36  196.77       3.07              193.69             0.00

Comparar francés y alemán para cada préstamo

In [ ]:
comparacion = []

for _, fila in datos.iterrows():

    id_prestamo = fila["ID"]

    cuadro_f = cuadro_frances(
        fila["capital_prestado"],
        fila["interes_anual"],
        fila["num_meses"]
    )

    cuadro_a = cuadro_aleman(
        fila["capital_prestado"],
        fila["interes_anual"],
        fila["num_meses"]
    )

    intereses_frances = cuadro_f["Intereses"].sum()
    intereses_aleman = cuadro_a["Intereses"].sum()

    mejor = "Francés"

    if intereses_aleman < intereses_frances:
        mejor = "Alemán"

    comparacion.append([
        id_prestamo,
        round(intereses_frances, 2),
        round(intereses_aleman, 2),
        mejor
    ])

comparacion = pd.DataFrame(
    comparacion,
    columns=[
        "ID",
        "Intereses_Frances",
        "Intereses_Aleman",
        "Metodo_Recomendado"
    ]
)

comparacion.head()

       ID  Intereses_Frances  Intereses_Aleman Metodo_Recomendado
0  O77MPJ            2235.01           2047.86             Alemán
1  IYOL1S            4184.01           4058.34             Alemán
2  FRMZVN            2641.59           2523.72             Alemán
3  YKHXVY           12336.41          11364.08             Alemán
4  NHDJTK            2579.50           2463.50             Alemán